name: Update m3u8 Link

on:
  schedule:
    - cron: '0 * * * *'  # Hər saat bir dəfə işləsin
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install yt-dlp
      run: pip install yt-dlp

    - name: Get m3u8 link
      id: 3g2EfhnmTkU
      run: |
        m3u8_link=$(yt-dlp -g "https://www.youtube.com/watch?v=3g2EfhnmTkU")
        echo "::set-output name=m3u8_link::$m3u8_link"

    - name: Update m3u8 file
      run: |
        echo "${{ steps.get_m3u8.outputs.m3u8_link }}" > video.m3u8

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add video.m3u8
        git commit -m "Update m3u8 link"
        git push
